version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: max
      # MONGO_INITDB_ROOT_PASSWORD: secret
      # - MONGO_INITDB_ROOT_USERNAME=max
    env_file:
      - ./env/mongo.env
    # networks:
    #   - goals-net
  backend:
    build: ./backend
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#      args:
#        - arg=value 
#    image: 'goals-be'
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
#      - $(pwd):/app
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    # image: 'goals-fe'
    ports:
      - '3000:3000'
    volumes:
      #-  $(pwd)/src:/app/src
      -  ./frontend/src:/app/src
    stdin_open: true
    tty: true
    # it 
    depends_on:
      - backend

volumes:
  data:
  logs: